version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: "1111"
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  spring:
    build: ./backend-spring
    container_name: local-spring
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://local-mysql:3306/app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: "1111"
    depends_on:
      mysql:
        condition: service_healthy

  fastapi:
    build: ./ai-fastapi
    container_name: local-fastapi
    env_file:
    - ./ai-fastapi/.env.local
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy  # healthcheck 있어야 이게 동작함        

  frontend:
    build: ./frontend
    container_name: local-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:8080
      - VITE_AI_BASE=http://localhost:8000
    depends_on:
      - spring
      - fastapi

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped


volumes:
  mysql_data:
  redis_data: